# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-07 13:28
from __future__ import absolute_import
from __future__ import unicode_literals

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLMetatags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_column=b'path', help_text=b"Could be a url name or a path. Begin paths with '/'", max_length=255)),
                ('title', models.TextField(blank=True, help_text=b'Will be stuck within the title attribute', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text=b'Meta-Description', null=True)),
                ('keywords', models.TextField(blank=True, help_text=b'Meta-Keywords', null=True)),
                ('google_pagetrack_category', models.CharField(blank=True, max_length=55, null=True)),
                ('google_pagetrack_customvar', models.CharField(blank=True, max_length=55, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name_plural': 'URL Metatags',
            },
            managers=[
                ('objects', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='urlmetatags',
            unique_together=set([('site', 'url')]),
        ),
    ]
